import { motion } from "framer-motion";
import { Download, Filter, Package, TrendingUp, Users, WalletCards } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import PageContainer from "../../../components/ui/PageContainer";

const revenue = [{month:"Mar",sales:4200000,expenses:2600000,profit:1600000},{month:"Apr",sales:5100000,expenses:3100000,profit:2000000},{month:"May",sales:5900000,expenses:3500000,profit:2400000},{month:"Jun",sales:6400000,expenses:3900000,profit:2500000},{month:"Jul",sales:7200000,expenses:4200000,profit:3000000},{month:"Aug",sales:8100000,expenses:4700000,profit:3400000}];
const employees = [{name:"Adebayo James",sales:4200000,activities:68,attendance:96},{name:"Grace Okafor",sales:3150000,activities:51,attendance:98},{name:"Michael Ade",sales:2700000,activities:24,attendance:94},{name:"Sarah Bello",sales:1980000,activities:43,attendance:91}];
const inventory = [{name:"Solar Panel 300W",value:2180000,velocity:88},{name:"Lithium 5kWh",value:3560000,velocity:71},{name:"2KVA Hybrid Inverter",value:1740000,velocity:62},{name:"CCTV Camera",value:820000,velocity:54},{name:"Router",value:430000,velocity:41}];

export default function ReportsPage(){
 const [period,setPeriod]=useState("This quarter"); const [tab,setTab]=useState("Financials");
 const totalSales=useMemo(()=>revenue.reduce((s,r)=>s+r.sales,0),[]); const totalProfit=useMemo(()=>revenue.reduce((s,r)=>s+r.profit,0),[]);
 return <PageContainer><div className="min-h-full space-y-6 bg-[#f8fafc] pb-14">
  <header className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-sky-600">Analytics Hub</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Reports & business intelligence</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">One reporting surface for financial health, team performance, inventory velocity and attendance. The same date filter drives every view.</p></div><div className="flex flex-wrap gap-3"><select value={period} onChange={e=>setPeriod(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold"><option>Last 30 days</option><option>This quarter</option><option>This year</option></select><button className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white hover:bg-slate-800"><Download size={16}/> Export</button></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<WalletCards/>} label="Revenue" value={`₦${(totalSales/1e6).toFixed(1)}m`} tone="sky"/><Stat icon={<TrendingUp/>} label="Net profit" value={`₦${(totalProfit/1e6).toFixed(1)}m`} tone="emerald"/><Stat icon={<Package/>} label="Stock value" value="₦8.7m" tone="violet"/><Stat icon={<Users/>} label="Team attendance" value="95.1%" tone="amber"/></div></header>
  <div className="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-2 shadow-sm">{["Financials","Employee Performance","Inventory Health","Attendance"].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-xl px-4 py-2.5 text-sm font-bold transition ${tab===x?"bg-slate-950 text-white":"text-slate-500 hover:bg-slate-100"}`}>{x}</button>)}</div>
  {tab==="Financials" && <div className="grid gap-6 xl:grid-cols-[1.7fr_1fr]"><ChartCard title="Revenue, expenses & profit" subtitle={period}><ResponsiveContainer width="100%" height={330}><LineChart data={revenue}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis dataKey="month"/><YAxis tickFormatter={v=>`₦${Math.round(v/1e6)}m`}/><Tooltip/><Line type="monotone" dataKey="sales" stroke="#0ea5e9" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="expenses" stroke="#f59e0b" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="profit" stroke="#10b981" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></ChartCard><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><Insight title="Gross margin" value="41.9%" detail="Up 3.8 pts from prior period" tone="emerald"/><Insight title="Expense ratio" value="58.0%" detail="Operations are within target" tone="sky"/><Insight title="Outstanding receivables" value="₦1.24m" detail="23 invoices need follow-up" tone="amber"/></div></div>}
  {tab==="Employee Performance" && <ReportTable title="Revenue generated per employee" headers={["Employee","Revenue","Activities","Attendance","Signal"]} rows={employees.map(e=>[e.name,`₦${e.sales.toLocaleString()}`,String(e.activities),e.attendance+"%",e.sales>3000000?"Top performer":"On track"])} />}
  {tab==="Inventory Health" && <div className="grid gap-6 lg:grid-cols-2"><ChartCard title="Inventory valuation" subtitle="Current warehouse value"><ResponsiveContainer width="100%" height={330}><BarChart data={inventory}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis dataKey="name" angle={-18} textAnchor="end" height={70}/><YAxis tickFormatter={v=>`₦${Math.round(v/1e6)}m`}/><Tooltip/><Bar dataKey="value" fill="#8b5cf6" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ReportTable title="Fastest-moving items" headers={["Product","Stock value","Velocity","Health"]} rows={inventory.map(i=>[i.name,`₦${i.value.toLocaleString()}`,i.velocity+" units/wk",i.velocity>70?"Fast":"Normal"])} /></div>}
  {tab==="Attendance" && <ReportTable title="Attendance & timesheets" headers={["Employee","Work days","Hours","Late arrivals","Attendance"]} rows={employees.map(e=>[e.name,"22","176",e.attendance<95?"4":"1",e.attendance+"%"])} />}
 </div></PageContainer>
}
function ChartCard({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <motion.section whileHover={{y:-2}} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="font-black text-slate-950">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><Filter size={17} className="text-slate-400"/></div>{children}</motion.section>}
function Stat({icon,label,value,tone}:{icon:ReactNode;label:string;value:string;tone:"sky"|"emerald"|"violet"|"amber"}){const c={sky:"bg-sky-50 text-sky-700",emerald:"bg-emerald-50 text-emerald-700",violet:"bg-violet-50 text-violet-700",amber:"bg-amber-50 text-amber-700"}[tone];return <div className={`rounded-2xl p-4 ${c}`}><div>{icon}</div><p className="mt-3 text-xs font-black uppercase tracking-wider opacity-70">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
function Insight({title,value,detail,tone}:{title:string;value:string;detail:string;tone:"emerald"|"sky"|"amber"}){const c={emerald:"bg-emerald-50 text-emerald-900",sky:"bg-sky-50 text-sky-900",amber:"bg-amber-50 text-amber-900"}[tone];return <div className={`rounded-2xl p-5 ${c}`}><p className="text-xs font-bold opacity-70">{title}</p><p className="mt-2 text-3xl font-black">{value}</p><p className="mt-2 text-xs opacity-70">{detail}</p></div>}
function ReportTable({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="font-black text-slate-950">{title}</h2><p className="mt-1 text-xs text-slate-500">Exportable operational report</p></div><div className="overflow-x-auto"><table className="min-w-[720px] w-full"><thead className="bg-slate-50"><tr>{headers.map(h=><th key={h} className="px-5 py-4 text-left text-[10px] font-black uppercase tracking-wider text-slate-400">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><motion.tr whileHover={{backgroundColor:"#f8fafc"}} key={i} className="border-t border-slate-100">{row.map((cell,j)=><td key={j} className="px-5 py-4 text-sm font-semibold text-slate-700">{cell}</td>)}</motion.tr>)}</tbody></table></div></section>}
