import "./ProductDrawer.css";
import { AnimatePresence, motion } from "framer-motion";
import { Barcode, ImagePlus, Layers3, MapPin, QrCode, Save, Trash2, X, Plus, Minus } from "lucide-react";
import { useEffect, useState } from "react";
import QRCode from "qrcode";
import JsBarcode from "jsbarcode";
import type { InventoryItem, ProductUnitVariant } from "../../modules/inventory/types/InventoryItem";
import { requireDesktopApi, type UnitType } from "../../lib/desktopApi";
type Props={product:InventoryItem|null;onClose:()=>void;onSave:(product:InventoryItem)=>Promise<void>;onDelete:(id:string)=>Promise<void>};
const fallbackUnits=["PCS","PACKET","DOZEN","CARTON","BOX","BAG","BOTTLE","CAN","KG","G","L","ML"];
export default function ProductDrawer({product,onClose,onSave,onDelete}:Props){
 const [draft,setDraft]=useState<InventoryItem|null>(product); const [saving,setSaving]=useState(false); const [qr,setQr]=useState(""); const [units,setUnits]=useState<UnitType[]>([]); const [barcodeRef]=useState(()=>({current:null as SVGSVGElement|null}));
 useEffect(()=>setDraft(product),[product]);
 useEffect(()=>{void requireDesktopApi().erp.units.list().then(setUnits).catch(()=>setUnits([]))},[]);
 useEffect(()=>{if(!draft)return;const value=draft.barcode?.trim()||draft.sku;void QRCode.toDataURL(value,{width:180,margin:1}).then(setQr).catch(()=>setQr(""));if(barcodeRef.current&&value){try{JsBarcode(barcodeRef.current,value,{format:"CODE128",displayValue:true,height:42,margin:0,fontSize:11})}catch{}}},[draft,barcodeRef]);
 if(!product||!draft)return null;
 const set=<K extends keyof InventoryItem>(key:K,value:InventoryItem[K])=>setDraft(current=>current?{...current,[key]:value}:current);
 const imageFromFile=(file:File)=>{const reader=new FileReader();reader.onload=()=>set("imageUrl",String(reader.result));reader.readAsDataURL(file)};
 const variants=draft.unitVariants?.length?draft.unitVariants:[{code:draft.baseUnitCode||draft.unit||"PCS",name:draft.unit||"PCS",conversionToBase:1,sellingPrice:draft.sellingPrice,isDefault:true}];
 const setVariants=(next:ProductUnitVariant[])=>set("unitVariants",next);
 const save=async()=>{setSaving(true);try{await onSave({...draft,unitVariants:variants,baseUnitCode:draft.baseUnitCode||draft.unit||"PCS"});}finally{setSaving(false)}};
 return <AnimatePresence><motion.div className="fixed inset-0 z-[70] bg-slate-950/30 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}><motion.aside initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}} transition={{type:"spring",stiffness:280,damping:30}} onMouseDown={event=>event.stopPropagation()} className="absolute right-0 top-0 flex h-full w-full max-w-4xl flex-col bg-white shadow-2xl">
 <div className="flex items-center justify-between border-b px-5 py-4 sm:px-7"><div><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-500">Product editor</p><h2 className="mt-1 break-words text-xl font-black text-slate-950">{draft.itemName||"New product"}</h2></div><button onClick={onClose} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100"><X/></button></div>
 <div className="flex-1 overflow-y-auto p-5 sm:p-7"><div className="grid gap-6 lg:grid-cols-[190px_1fr]"><div><div className="relative h-48 overflow-hidden rounded-3xl border bg-gradient-to-br from-indigo-50 via-white to-sky-50">{draft.imageUrl?<img src={draft.imageUrl} alt={draft.itemName||"Product"} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-indigo-200"><ImagePlus size={42}/></div>}</div><label className="mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed px-3 py-2.5 text-xs font-bold text-slate-600"><ImagePlus size={15}/> Add image<input type="file" accept="image/*" className="hidden" onChange={event=>{const file=event.target.files?.[0];if(file)imageFromFile(file)}}/></label><div className="mt-4 rounded-2xl border bg-slate-50 p-3"><label className="flex items-center justify-between gap-3 text-xs font-black"><span>Track stock</span><input type="checkbox" checked={draft.isTracked!==false} onChange={e=>set("isTracked",e.target.checked)} className="h-5 w-5"/></label><p className="mt-2 text-[11px] leading-5 text-slate-500">Turn off for unlimited food/service items such as scoops or portions.</p></div></div>
 <div className="grid gap-4 sm:grid-cols-2"><label className="field">Product name<input autoFocus value={draft.itemName} onChange={event=>set("itemName",event.target.value)}/></label><label className="field">Brand<input value={draft.brand??""} onChange={event=>set("brand",event.target.value)}/></label><label className="field">SKU<input value={draft.sku} onChange={event=>set("sku",event.target.value)}/></label><label className="field">Barcode<input value={draft.barcode??""} onChange={event=>set("barcode",event.target.value)}/></label><label className="field">Category<input value={draft.category} onChange={event=>set("category",event.target.value)}/></label><label className="field">Warehouse<input value={draft.warehouse} onChange={event=>set("warehouse",event.target.value)}/></label><label className="field">Base unit<select value={draft.baseUnitCode||draft.unit} onChange={event=>{set("baseUnitCode",event.target.value);set("unit",event.target.value)}}>{units.length?units.map(unit=><option key={unit.code} value={unit.code}>{unit.name} ({unit.code})</option>):fallbackUnits.map(unit=><option key={unit}>{unit}</option>)}</select></label><label className="field">Reorder level<input disabled={draft.isTracked===false} type="number" min="0" value={draft.reorderLevel} onChange={event=>set("reorderLevel",Number(event.target.value))}/></label></div></div>
 <div className="mt-6 grid gap-4 sm:grid-cols-3"><label className="field">Base quantity<input disabled={draft.isTracked===false} type="number" min="0" step="0.001" value={draft.quantity} onChange={event=>set("quantity",Number(event.target.value))}/></label><label className="field">Unit cost<input type="number" min="0" value={draft.unitCost} onChange={event=>set("unitCost",Number(event.target.value))}/></label><label className="field">Base retail price<input type="number" min="0" value={draft.sellingPrice} onChange={event=>set("sellingPrice",Number(event.target.value))}/></label></div>
 <label className="field mt-4">Description<textarea rows={3} value={draft.description??""} onChange={event=>set("description",event.target.value)}/></label>
 <section className="mt-7 rounded-3xl border bg-slate-50 p-5"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Layers3 size={18} className="text-indigo-600"/><h3 className="font-black">Selling units & pack sizes</h3></div><p className="mt-1 text-xs leading-5 text-slate-500">Example: 1 carton = 12 packets, 1 packet = 10 pieces. The factor is how many base units one selling unit represents.</p></div><button onClick={()=>setVariants([...variants,{code:"PACKET",name:"Packet",conversionToBase:1,sellingPrice:draft.sellingPrice,isDefault:false}])} className="inline-flex min-h-10 items-center gap-1 rounded-xl bg-indigo-600 px-3 text-xs font-black text-white"><Plus size={14}/> Add tier</button></div><div className="mt-4 space-y-3">{variants.map((variant,index)=><div key={`${variant.code}-${index}`} className="grid gap-2 rounded-2xl border bg-white p-3 sm:grid-cols-[1fr_1fr_1fr_1fr_auto]"><input value={variant.code} onChange={e=>setVariants(variants.map((v,i)=>i===index?{...v,code:e.target.value.toUpperCase()}:v))} placeholder="Code" className="rounded-xl border px-3 py-2 text-xs font-bold"/><input value={variant.name} onChange={e=>setVariants(variants.map((v,i)=>i===index?{...v,name:e.target.value}:v))} placeholder="Name" className="rounded-xl border px-3 py-2 text-xs"/><input type="number" min="0.000001" step="0.000001" value={variant.conversionToBase} onChange={e=>setVariants(variants.map((v,i)=>i===index?{...v,conversionToBase:Number(e.target.value)||1}:v))} placeholder="Base units" className="rounded-xl border px-3 py-2 text-xs font-bold"/><input type="number" min="0" value={variant.sellingPrice} onChange={e=>setVariants(variants.map((v,i)=>i===index?{...v,sellingPrice:Number(e.target.value)||0}:v))} placeholder="Selling price" className="rounded-xl border px-3 py-2 text-xs font-bold"/><button disabled={variants.length===1} onClick={()=>setVariants(variants.filter((_,i)=>i!==index))} className="grid h-10 w-10 place-items-center rounded-xl bg-rose-50 text-rose-600 disabled:opacity-30"><Minus size={15}/></button></div>)}</div></section>
 <div className="mt-7 grid gap-4 lg:grid-cols-2"><section className="rounded-3xl border bg-white p-5"><div className="flex items-center gap-2"><MapPin size={18} className="text-sky-600"/><h3 className="font-black">Spatial location</h3></div><div className="mt-4 flex flex-wrap items-center gap-2 text-sm font-bold text-slate-700"><span className="rounded-xl bg-sky-50 px-3 py-2 text-sky-700">{draft.warehouse||"Warehouse"}</span><span className="text-slate-300">→</span><span className="rounded-xl bg-indigo-50 px-3 py-2 text-indigo-700">Aisle</span><span className="text-slate-300">→</span><span className="rounded-xl bg-emerald-50 px-3 py-2 text-emerald-700">Bin</span></div></section><section className="rounded-3xl border bg-white p-5"><div className="flex items-center gap-2"><Barcode size={18} className="text-indigo-600"/><h3 className="font-black">Barcode & QR</h3></div><div className="mt-4 grid items-center gap-5 sm:grid-cols-[1fr_180px]"><div className="min-w-0 overflow-hidden rounded-2xl bg-slate-50 p-4"><svg ref={el=>{barcodeRef.current=el}} className="h-auto max-w-full"/></div>{qr?<img src={qr} alt="Product QR code" className="mx-auto h-44 w-44 rounded-2xl border"/>:<div className="flex h-44 items-center justify-center rounded-2xl bg-slate-50"><QrCode className="text-slate-300" size={52}/></div>}</div></section></div>
 </div>
 <div className="flex flex-col gap-2 border-t bg-white p-4 sm:flex-row sm:justify-between sm:p-5"><button onClick={()=>void onDelete(product.id)} className="inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-bold text-rose-600"><Trash2 size={17}/> Delete product</button><div className="flex gap-2"><button onClick={onClose} className="rounded-xl border px-4 py-3 text-sm font-bold text-slate-600">Cancel</button><button disabled={saving||!draft.itemName.trim()} onClick={()=>void save()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white shadow-lg disabled:opacity-50"><Save size={17}/>{saving?"Saving…":"Save & close"}</button></div></div>
 </motion.aside></motion.div></AnimatePresence>;
}
