import { motion } from "framer-motion";
import { Bell, Building2, Database, Globe2, Palette, Printer, Receipt, Save, ShieldCheck, SlidersHorizontal, Wifi, Wrench } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import PageContainer from "../../../components/ui/PageContainer";
import { useAuth } from "../../../auth/AuthContext";
import { requireDesktopApi, type PrinterInfo, type SettingRecord } from "../../../lib/desktopApi";
const sections=[{id:"general",label:"General",icon:Building2},{id:"hardware",label:"Hardware",icon:Printer},{id:"pos",label:"POS rules",icon:Receipt},{id:"security",label:"Security",icon:ShieldCheck},{id:"appearance",label:"Appearance",icon:Palette},{id:"localization",label:"Localization",icon:Globe2},{id:"notifications",label:"Notifications",icon:Bell},{id:"data",label:"Data & maintenance",icon:Database}] as const;type Section=(typeof sections)[number]["id"];
type SettingsState={general:{businessName:string;receiptFooter:string};hardware:{defaultPrinter:string;receiptWidth:string};pos:{taxRate:number;requireCustomerForCredit:boolean;warnNegativeStock:boolean;autoPrint:boolean};security:{managerOverrideRequired:boolean;refundsRequireAdmin:boolean};appearance:{theme:string;accent:string;sounds:boolean;animations:boolean};localization:{currency:string;timezone:string;dateFormat:string};notifications:{lowStock:boolean;paymentReminders:boolean;securityEvents:boolean}};
const defaults:SettingsState={general:{businessName:"Ablect Technologies",receiptFooter:"Thank you for your patronage."},hardware:{defaultPrinter:"",receiptWidth:"80mm"},pos:{taxRate:7.5,requireCustomerForCredit:true,warnNegativeStock:true,autoPrint:false},security:{managerOverrideRequired:true,refundsRequireAdmin:true},appearance:{theme:"system",accent:"indigo",sounds:true,animations:true},localization:{currency:"NGN",timezone:"Africa/Lagos",dateFormat:"DD/MM/YYYY"},notifications:{lowStock:true,paymentReminders:true,securityEvents:true}};
export default function SettingsControlCenter(){const api=useMemo(()=>requireDesktopApi(),[]);const{user}=useAuth();const[section,setSection]=useState<Section>("general");const[state,setState]=useState<SettingsState>(defaults);const[printers,setPrinters]=useState<PrinterInfo[]>([]);const[roles,setRoles]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[saved,setSaved]=useState(false);
 useEffect(()=>{let mounted=true;void Promise.all([api.settings.all(),api.hardware.printers.list(),api.erp.admin.roles()]).then(([records,printerRows,roleRows])=>{if(!mounted)return;const next=structuredClone(defaults);for(const record of records as SettingRecord[])if(record.key in next)Object.assign(next[record.key as keyof SettingsState],record.value);setState(next);setPrinters(printerRows);setRoles(roleRows as any[])}).catch(e=>mounted&&setMessage(e instanceof Error?e.message:"Unable to load settings.")).finally(()=>mounted&&setLoading(false));return()=>{mounted=false}},[api]);
 const update=<K extends keyof SettingsState>(key:K,patch:Partial<SettingsState[K]>)=>setState(current=>({...current,[key]:{...current[key],...patch}}));
 const save=async()=>{try{for(const[key,value]of Object.entries(state))await api.settings.save(key,value as Record<string,unknown>,user?.id);setSaved(true);setMessage("Settings saved to the MySQL control engine.");window.setTimeout(()=>setSaved(false),2000)}catch(e){setMessage(e instanceof Error?e.message:"Unable to save settings.")}};
 const testPrint=async()=>{try{await api.hardware.receipt.print({businessName:state.general.businessName,invoiceNumber:"TEST-RECEIPT",date:new Date().toLocaleString("en-NG"),customerName:"Printer Test",items:[{name:"Test item",quantity:1,unit:"PCS",unitPrice:100}],subtotal:100,discount:0,tax:0,total:100,paid:100,change:0,paymentMethod:"Cash",footer:state.general.receiptFooter,printerName:state.hardware.defaultPrinter,receiptWidth:state.hardware.receiptWidth});setMessage("Test receipt sent successfully.")}catch(e){setMessage(e instanceof Error?e.message:"Printer test failed.")}};
 if(loading)return <PageContainer><div className="grid min-h-[70vh] place-items-center text-sm font-bold text-slate-500">Loading control engine…</div></PageContainer>;
 return <PageContainer><div className="min-h-full bg-[#f8fafc] pb-14"><header className="mb-6 rounded-[2rem] bg-gradient-to-br from-slate-950 to-indigo-950 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-300">Super-admin control engine</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Settings & configuration</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Hardware, POS rules, permissions, branding, localisation, alerts and maintenance in one persistent control centre.</p></div><button onClick={()=>void save()} className="min-h-12 rounded-2xl bg-cyan-400 px-5 text-sm font-black text-slate-950">{saved?"Saved":"Save all changes"}</button></div></header>{message&&<div className="mb-5 rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-sm font-semibold text-indigo-900">{message}</div>}<div className="grid gap-6 lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="h-fit rounded-3xl border bg-white p-3 shadow-sm lg:sticky lg:top-5">{sections.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setSection(id)} className={`mb-1 flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-black ${section===id?"bg-slate-950 text-white":"text-slate-600 hover:bg-slate-50"}`}><Icon size={18}/>{label}</button>)}</aside><main className="min-w-0"><motion.section key={section} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="rounded-3xl border bg-white p-5 shadow-sm sm:p-7">
 {section==="general"&&<Panel title="Business identity" icon={<Building2/>}><div className="grid gap-5 sm:grid-cols-2"><Field label="Business name" value={state.general.businessName} onChange={v=>update("general",{businessName:v})}/><Field label="Receipt footer" value={state.general.receiptFooter} onChange={v=>update("general",{receiptFooter:v})}/></div><Info text="Brand assets remain in Electron client configuration; operational settings are persisted in MySQL."/></Panel>}
 {section==="hardware"&&<Panel title="Hardware command centre" icon={<Printer/>}><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-slate-50 p-5"><p className="text-sm font-black">Default receipt printer</p><select value={state.hardware.defaultPrinter} onChange={e=>update("hardware",{defaultPrinter:e.target.value})} className="mt-3 h-12 w-full rounded-xl border bg-white px-3 text-sm font-bold"><option value="">System printer dialog</option>{printers.map(p=><option key={p.name} value={p.name}>{p.displayName||p.name}{p.isDefault?" · Default":""}</option>)}</select><p className="mt-2 text-xs leading-5 text-slate-500">Xprinter and other Windows printers are detected through Electron's native print engine.</p><button onClick={()=>void testPrint()} className="mt-4 min-h-11 rounded-xl bg-slate-950 px-4 text-xs font-black text-white"><Printer size={15} className="mr-1 inline"/> Test print</button></div><div className="rounded-3xl bg-slate-50 p-5"><p className="text-sm font-black">Receipt width</p><div className="mt-3 grid grid-cols-2 gap-2">{["58mm","80mm"].map(w=><button key={w} onClick={()=>update("hardware",{receiptWidth:w})} className={`min-h-12 rounded-xl border text-sm font-black ${state.hardware.receiptWidth===w?"border-indigo-600 bg-indigo-600 text-white":"bg-white"}`}>{w}</button>)}</div><div className="mt-4 rounded-2xl bg-white p-4"><p className="text-xs font-bold text-slate-400">Detected printers</p><p className="mt-1 text-2xl font-black">{printers.length}</p></div></div></div></Panel>}
 {section==="pos"&&<Panel title="POS rules & checkout engine" icon={<Receipt/>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Default tax rate (%)" value={String(state.pos.taxRate)} onChange={v=>update("pos",{taxRate:Number(v)||0})}/><Toggle title="Auto-print" detail="Print after checkout when a default printer is selected." checked={state.pos.autoPrint} onChange={v=>update("pos",{autoPrint:v})}/><Toggle title="Require customer for credit" detail="Credit transactions require a customer record." checked={state.pos.requireCustomerForCredit} onChange={v=>update("pos",{requireCustomerForCredit:v})}/><Toggle title="Block negative stock" detail="Prevent checkout above available stock." checked={state.pos.warnNegativeStock} onChange={v=>update("pos",{warnNegativeStock:v})}/></div><Info text="Dynamic units are supported: pieces, packets, dozens, cartons, boxes, bags, bottles, cans, KG, G and L/ML."/></Panel>}
 {section==="security"&&<Panel title="Security, roles & refund rules" icon={<ShieldCheck/>}><div className="grid gap-4 sm:grid-cols-2"><Toggle title="Manager override" detail="Sensitive discounts and restricted actions require elevated approval." checked={state.security.managerOverrideRequired} onChange={v=>update("security",{managerOverrideRequired:v})}/><Toggle title="Admin-only paid refunds" detail="Completed paid sales stay protected from cashier-level refunds." checked={state.security.refundsRequireAdmin} onChange={v=>update("security",{refundsRequireAdmin:v})}/></div><div className="mt-6 overflow-x-auto rounded-2xl border"><table className="min-w-[620px] w-full"><thead className="bg-slate-50"><tr>{["Role","Type","Module"].map(h=><th key={h} className="px-4 py-3 text-left text-[10px] font-black uppercase tracking-wider text-slate-400">{h}</th>)}</tr></thead><tbody>{roles.map((r:any)=><tr key={`${r.id}-${r.module_name||"role"}`} className="border-t"><td className="px-4 py-3 text-sm font-black">{r.name}</td><td className="px-4 py-3 text-xs text-slate-500">{r.is_system?"System":"Custom"}</td><td className="px-4 py-3 text-xs font-bold text-indigo-600">{r.module_name||"Role policy"}</td></tr>)}</tbody></table></div></Panel>}
 {section==="appearance"&&<Panel title="Experience & visual behaviour" icon={<Palette/>}><div className="grid gap-5 sm:grid-cols-2"><Select label="Theme" value={state.appearance.theme} options={["system","light","dark"]} onChange={v=>update("appearance",{theme:v})}/><Select label="Accent" value={state.appearance.accent} options={["indigo","cyan","emerald","violet","amber"]} onChange={v=>update("appearance",{accent:v})}/><Toggle title="Sound feedback" detail="Non-blocking audio cues for scans, saves and completed sales." checked={state.appearance.sounds} onChange={v=>update("appearance",{sounds:v})}/><Toggle title="Animations" detail="Enable motion and micro-interactions." checked={state.appearance.animations} onChange={v=>update("appearance",{animations:v})}/></div></Panel>}
 {section==="localization"&&<Panel title="Regional settings" icon={<Globe2/>}><div className="grid gap-5 sm:grid-cols-2"><Select label="Currency" value={state.localization.currency} options={["NGN","USD","GBP"]} onChange={v=>update("localization",{currency:v})}/><Select label="Timezone" value={state.localization.timezone} options={["Africa/Lagos","UTC","Europe/London"]} onChange={v=>update("localization",{timezone:v})}/><Select label="Date format" value={state.localization.dateFormat} options={["DD/MM/YYYY","MM/DD/YYYY","YYYY-MM-DD"]} onChange={v=>update("localization",{dateFormat:v})}/></div></Panel>}
 {section==="notifications"&&<Panel title="Operational alerts" icon={<Bell/>}><div className="space-y-3"><Toggle title="Low-stock alerts" detail="Notify inventory staff when products reach reorder level." checked={state.notifications.lowStock} onChange={v=>update("notifications",{lowStock:v})}/><Toggle title="Payment reminders" detail="Flag unpaid balances for finance follow-up." checked={state.notifications.paymentReminders} onChange={v=>update("notifications",{paymentReminders:v})}/><Toggle title="Security events" detail="Surface role, login and permission changes." checked={state.notifications.securityEvents} onChange={v=>update("notifications",{securityEvents:v})}/></div></Panel>}
 {section==="data"&&<Panel title="Data & maintenance" icon={<Database/>}><div className="grid gap-4 sm:grid-cols-3"><Stat icon={<Wifi/>} label="Database" value="MySQL"/><Stat icon={<Wrench/>} label="Schema" value="Migrated"/><Stat icon={<SlidersHorizontal/>} label="Control" value="Local"/></div><Info text="Migrations run at application startup. Product images, dynamic units, settings and split payments are additive."/></Panel>}
 </motion.section></main></div></div></PageContainer>}
function Panel({title,icon,children}:{title:string;icon:ReactNode;children:ReactNode}){return <div><div className="mb-6 flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-indigo-50 text-indigo-600">{icon}</div><div><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm text-slate-500">Persistent settings for the ERP control layer.</p></div></div>{children}</div>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-400">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border px-4 py-3 text-sm font-semibold outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50"/></label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-400">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border bg-white px-4 py-3 text-sm font-semibold">{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Toggle({title,detail,checked,onChange}:{title:string;detail:string;checked:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-start gap-4 rounded-2xl border p-4"><div className="min-w-0 flex-1"><p className="text-sm font-black">{title}</p><p className="mt-1 break-words text-xs leading-5 text-slate-500">{detail}</p></div><button onClick={()=>onChange(!checked)} className={`relative mt-1 h-7 w-12 shrink-0 rounded-full p-1 ${checked?"bg-indigo-600":"bg-slate-200"}`}><span className={`block h-5 w-5 rounded-full bg-white shadow transition ${checked?"translate-x-5":""}`}/></button></div>}
function Info({text}:{text:string}){return <div className="mt-6 rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-xs leading-5 text-indigo-800">{text}</div>}
function Stat({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-indigo-600">{icon}</div><p className="mt-3 text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
