import { motion } from "framer-motion";
import { Bell, Building2, Database, Globe2, Receipt, Save, ShieldCheck } from "lucide-react";
import { useState, type ReactNode } from "react";
import PageContainer from "../../../components/ui/PageContainer";
import { useAdminStore } from "../store/AdminStore";

const sections = [{id:"general",label:"General",icon:Building2},{id:"localization",label:"Localization",icon:Globe2},{id:"sales",label:"POS & Sales",icon:Receipt},{id:"security",label:"Security & audit",icon:ShieldCheck},{id:"notifications",label:"Notifications",icon:Bell},{id:"data",label:"Data & maintenance",icon:Database}] as const;

export default function SettingsPage(){
 const [section,setSection]=useState<(typeof sections)[number]["id"]>("general"); const [saved,setSaved]=useState(false); const [discountPin,setDiscountPin]=useState(true); const [autoBackup,setAutoBackup]=useState(true); const auditLogs=useAdminStore(s=>s.auditLogs);
 const save=()=>{setSaved(true);window.setTimeout(()=>setSaved(false),1800)};
 return <PageContainer><div className="min-h-full space-y-6 bg-[#f8fafc] pb-14">
  <header className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-indigo-600">System administration</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Settings & configuration</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Configure company identity, currency, POS controls, security, notifications and operational safeguards without mixing unrelated settings.</p></div><button onClick={save} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white hover:bg-indigo-700"><Save size={17}/>{saved?"Saved":"Save changes"}</button></div></header>
  <div className="grid gap-6 lg:grid-cols-[240px_1fr]"><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">{sections.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setSection(id)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-bold transition ${section===id?"bg-indigo-50 text-indigo-700":"text-slate-600 hover:bg-slate-50"}`}><Icon size={17}/>{label}</button>)}</aside><main className="min-w-0">
  {section==="general"&&<Panel title="Company identity" description="Information shown across receipts, invoices, reports and the ERP shell."><div className="grid gap-5 sm:grid-cols-2"><Input label="Company name" value="Ablect Technologies"/><Input label="Business email" value="ablecttechnologies@gmail.com"/><Input label="Phone" value="08108113426"/><Input label="Tax / CAC ID" value="ABLECT TECHNOLOGIES LTD"/><div className="sm:col-span-2"><label className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-400">Company logo</label><div className="flex flex-wrap items-center gap-4 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-indigo-600 font-black text-white">A</div><div className="min-w-0"><p className="text-sm font-bold text-slate-800">Upload brand mark</p><p className="text-xs text-slate-500">PNG, SVG or JPG. Used on documents and receipts.</p></div><button className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-slate-700">Choose file</button></div></div></div></Panel>}
  {section==="localization"&&<Panel title="Localization" description="Control the default presentation of dates, currency and time. Existing transaction values are never silently converted."><div className="grid gap-5 sm:grid-cols-2"><Select label="Default currency" options={["NGN — Nigerian Naira","USD — US Dollar","GBP — Pound Sterling"]}/><Select label="Timezone" options={["Africa/Lagos","UTC","Europe/London"]}/><Select label="Date format" options={["DD/MM/YYYY","MM/DD/YYYY","YYYY-MM-DD"]}/><Select label="Number format" options={["1,234,567.89","1.234.567,89"]}/></div></Panel>}
  {section==="sales"&&<Panel title="POS & Sales controls" description="Rules that affect how cashiers and sales teams complete transactions."><div className="space-y-4"><Toggle title="Manager PIN for discounts" detail="Cashiers must obtain an approved manager PIN before applying restricted discounts." checked={discountPin} onChange={setDiscountPin}/><Toggle title="Require customer on credit sale" detail="Prevent credit invoices from being posted without a linked customer." checked={true} onChange={()=>{}}/><Toggle title="Warn before negative stock" detail="Show a blocking warning when a sale would exceed available stock." checked={true} onChange={()=>{}}/><Input label="Receipt footer" value="Thank you for doing business with Ablect Technologies."/><Input label="Default tax rate" value="7.5%"/></div></Panel>}
  {section==="security"&&<Panel title="Security & audit trail" description="Every sensitive action should be attributable to a user and reference."><div className="mb-6 grid gap-4 sm:grid-cols-3"><SecurityStat label="Audit events" value={auditLogs.length.toString()}/><SecurityStat label="2FA protected" value="3 / 4"/><SecurityStat label="Failed actions" value="1"/></div><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-[720px] w-full"><thead className="bg-slate-50"><tr>{["Time","Actor","Action","Module","Severity"].map(h=><th key={h} className="px-4 py-3 text-left text-[10px] font-black uppercase tracking-wider text-slate-400">{h}</th>)}</tr></thead><tbody>{auditLogs.map(log=><tr key={log.id} className="border-t border-slate-100"><td className="px-4 py-3 text-xs text-slate-500">{log.timestamp}</td><td className="px-4 py-3 text-sm font-bold text-slate-700">{log.actor}</td><td className="px-4 py-3 text-sm text-slate-600">{log.action}</td><td className="px-4 py-3 text-xs font-bold text-slate-500">{log.module}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${log.severity==="Critical"?"bg-rose-50 text-rose-700":log.severity==="Warning"?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{log.severity}</span></td></tr>)}</tbody></table></div></Panel>}
  {section==="notifications"&&<Panel title="Notifications" description="Keep operational alerts useful instead of noisy."><div className="space-y-4"><Toggle title="Low-stock alerts" detail="Notify inventory managers when items reach their reorder point." checked={true} onChange={()=>{}}/><Toggle title="Payment reminders" detail="Notify finance when invoices remain unpaid past their due date." checked={true} onChange={()=>{}}/><Toggle title="Security events" detail="Notify administrators about role, login and permission changes." checked={true} onChange={()=>{}}/></div></Panel>}
  {section==="data"&&<Panel title="Data & maintenance" description="Operational safeguards for a desktop-first ERP. Destructive actions remain explicit."><div className="space-y-4"><Toggle title="Automatic local backup" detail="Keep a local recovery copy when the application is running offline." checked={autoBackup} onChange={setAutoBackup}/><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="text-sm font-black text-amber-900">Maintenance zone</p><p className="mt-1 text-xs leading-5 text-amber-800">Database repair, cache reset and migration tools should only be exposed to Super Admins. They are intentionally not wired to a destructive action from this screen.</p></div></div></Panel>}
 </main></div></div></PageContainer>;
}
function Panel({title,description,children}:{title:string;description:string;children:ReactNode}){return <motion.section initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div className="mb-6"><h2 className="text-xl font-black text-slate-950">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{description}</p></div>{children}</motion.section>}
function Input({label,value}:{label:string;value:string}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-400">{label}</span><input defaultValue={value} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-800 outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50"/></label>}
function Select({label,options}:{label:string;options:string[]}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-400">{label}</span><select className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-800">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Toggle({title,detail,checked,onChange}:{title:string;detail:string;checked:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-start gap-4 rounded-2xl border border-slate-200 p-4"><div className="min-w-0 flex-1"><p className="text-sm font-black text-slate-800">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div><button onClick={()=>onChange(!checked)} className={`relative mt-1 h-7 w-12 shrink-0 rounded-full p-1 transition ${checked?"bg-indigo-600":"bg-slate-200"}`} aria-pressed={checked}><span className={`block h-5 w-5 rounded-full bg-white shadow-sm transition ${checked?"translate-x-5":"translate-x-0"}`}/></button></div>}
function SecurityStat({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-xl font-black text-slate-950">{value}</p></div>}
