import { motion } from "framer-motion";
import { Bell, Building2, Database, Globe2, Palette, Printer, Receipt, Save, ShieldCheck, SlidersHorizontal, Wifi, Wrench } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import PageContainer from "../../../components/ui/PageContainer";
import { useAuth } from "../../../auth/AuthContext";
import { requireDesktopApi } from "../../../lib/desktopApi";

const tabs=["general","hardware","pos","security","appearance","localization","notifications","data"] as const;
type Tab=typeof tabs[number];
const labels:Record<Tab,string>={general:"General",hardware:"Hardware",pos:"POS rules",security:"Security",appearance:"Appearance",localization:"Localization",notifications:"Notifications",data:"Data & maintenance"};
const defaults:any={general:{businessName:"Ablect Technologies",receiptFooter:"Thank you for your patronage."},hardware:{defaultPrinter:"",receiptWidth:"80mm"},pos:{taxRate:7.5,requireCustomerForCredit:true,warnNegativeStock:true,autoPrint:false},security:{managerOverrideRequired:true,refundsRequireAdmin:true},appearance:{theme:"system",accent:"indigo",sounds:true,animations:true},localization:{currency:"NGN",timezone:"Africa/Lagos",dateFormat:"DD/MM/YYYY"},notifications:{lowStock:true,paymentReminders:true,securityEvents:true}};
export default function SettingsControlCenter(){const api=useMemo(()=>requireDesktopApi(),[]);const{user}=useAuth();const[tab,setTab]=useState<Tab>("general");const[data,setData]=useState<any>(defaults);const[printers,setPrinters]=useState<any[]>([]);const[roles,setRoles]=useState<any[]>([]);const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
 useEffect(()=>{let alive=true;Promise.all([api.settings.all(),api.hardware.printers.list(),api.erp.admin.roles()]).then(([records,printerRows,roleRows])=>{if(!alive)return;const next=structuredClone(defaults);for(const r of records as any[])if(r.key in next)Object.assign(next[r.key],r.value);setData(next);setPrinters(printerRows);setRoles(roleRows)}).catch(e=>alive&&setMessage(e instanceof Error?e.message:"Unable to load settings")).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[api]);
 const patch=(key:Tab,value:any)=>setData((d:any)=>({...d,[key]:{...d[key],...value}});
 const save=async()=>{setSaving(true);try{for(const[key,value]of Object.entries(data))await api.settings.save(key,value as Record<string,unknown>,user?.id);setMessage("Settings saved successfully.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to save settings")}finally{setSaving(false)}};
 const testPrint=async()=>{try{await api.hardware.receipt.print({businessName:data.general.businessName,invoiceNumber:"TEST-RECEIPT",date:new Date().toLocaleString("en-NG"),customerName:"Printer Test",items:[{name:"Test item",quantity:1,unit:"PCS",unitPrice:100}],subtotal:100,discount:0,tax:0,total:100,paid:100,change:0,paymentMethod:"Cash",footer:data.general.receiptFooter,printerName:data.hardware.defaultPrinter,receiptWidth:data.hardware.receiptWidth});setMessage("Test receipt sent successfully.")}catch(e){setMessage(e instanceof Error?e.message:"Printer test failed.")}};
 if(loading)return <PageContainer><div className="grid min-h-[70vh] place-items-center font-bold text-slate-500">Loading control engine…</div></PageContainer>;
 return <PageContainer><div className="min-h-full bg-[#f8fafc] pb-14"><header className="mb-6 rounded-[2rem] bg-gradient-to-br from-slate-950 to-indigo-950 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-300">Super-admin control engine</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Settings & configuration</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Hardware, POS rules, permissions, branding, localisation, alerts and maintenance in one persistent control centre.</p></div><button onClick={()=>void save()} disabled={saving} className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-cyan-400 px-5 text-sm font-black text-slate-950 disabled:opacity-50"><Save size={17}/>{saving?"Saving…":"Save all changes"}</button></div></header>{message&&<div className="mb-5 rounded-2xl bg-indigo-50 p-4 text-sm font-semibold text-indigo-900">{message}</div>}<div className="grid gap-6 lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="h-fit rounded-3xl border bg-white p-3 shadow-sm lg:sticky lg:top-5">{tabs.map(id=><button key={id} onClick={()=>setTab(id)} className={`mb-1 flex w-full rounded-2xl px-4 py-3 text-left text-sm font-black ${tab===id?"bg-slate-950 text-white":"text-slate-600 hover:bg-slate-50"}`}>{labels[id]}</button>)}</aside><main className="min-w-0"><motion.section key={tab} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="rounded-3xl border bg-white p-5 shadow-sm sm:p-7">
 {tab==="general"&&<Panel title="Business identity" icon={<Building2/>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Business name" value={data.general.businessName} onChange={v=>patch("general",{businessName:v})}/><Field label="Receipt footer" value={data.general.receiptFooter} onChange={v=>patch("general",{receiptFooter:v})}/></div></Panel>}
 {tab==="hardware"&&<Panel title="Hardware command centre" icon={<Printer/>}><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-slate-50 p-5"><Field label="Default printer" value={data.hardware.defaultPrinter} onChange={v=>patch("hardware",{defaultPrinter:v})}/><select value={data.hardware.defaultPrinter} onChange={e=>patch("hardware",{defaultPrinter:e.target.value})} className="mt-2 h-12 w-full rounded-xl border bg-white px-3 text-sm font-bold"><option value="">System printer dialog</option>{printers.map(p=><option key={p.name} value={p.name}>{p.displayName||p.name}{p.isDefault?" · Default":""}</option>)}</select><button onClick={()=>void testPrint()} className="mt-4 min-h-11 rounded-xl bg-slate-950 px-4 text-xs font-black text-white"><Printer size={15} className="mr-1 inline"/> Test print</button></div><div className="rounded-3xl bg-slate-50 p-5"><p className="text-sm font-black">Receipt width</p><div className="mt-3 grid grid-cols-2 gap-2">{["58mm","80mm"].map(w=><button key={w} onClick={()=>patch("hardware",{receiptWidth:w})} className={`min-h-12 rounded-xl border font-black ${data.hardware.receiptWidth===w?"bg-indigo-600 text-white":"bg-white"}`}>{w}</button>)}</div><p className="mt-4 text-xs text-slate-500">Detected printers: {printers.length}</p></div></div></Panel>}
 {tab==="pos"&&<Panel title="POS rules" icon={<Receipt/>}><div className="grid gap-3 sm:grid-cols-2"><Field label="Default tax rate (%)" value={String(data.pos.taxRate)} onChange={v=>patch("pos",{taxRate:Number(v)||0})}/><Toggle title="Auto-print" checked={data.pos.autoPrint} onChange={v=>patch("pos",{autoPrint:v})}/><Toggle title="Require customer for credit" checked={data.pos.requireCustomerForCredit} onChange={v=>patch("pos",{requireCustomerForCredit:v})}/><Toggle title="Block negative stock" checked={data.pos.warnNegativeStock} onChange={v=>patch("pos",{warnNegativeStock:v})}/></div><Info text="Dynamic units: PCS, packets, dozens, cartons, boxes, bags, bottles, cans, KG, G and L/ML are available."/></Panel>}
 {tab==="security"&&<Panel title="Security & permissions" icon={<ShieldCheck/>}><div className="grid gap-3 sm:grid-cols-2"><Toggle title="Manager override" checked={data.security.managerOverrideRequired} onChange={v=>patch("security",{managerOverrideRequired:v})}/><Toggle title="Admin-only paid refunds" checked={data.security.refundsRequireAdmin} onChange={v=>patch("security",{refundsRequireAdmin:v})}/></div><div className="mt-5 overflow-x-auto rounded-2xl border"><table className="min-w-[600px] w-full"><thead className="bg-slate-50"><tr><th className="px-4 py-3 text-left text-xs">Role</th><th className="px-4 py-3 text-left text-xs">Module</th></tr></thead><tbody>{roles.map((r:any)=><tr key={`${r.id}-${r.module_name||"role"}`} className="border-t"><td className="px-4 py-3 text-sm font-black">{r.name}</td><td className="px-4 py-3 text-xs text-indigo-600">{r.module_name||"Role policy"}</td></tr>)}</tbody></table></div></Panel>}
 {tab==="appearance"&&<Panel title="Appearance" icon={<Palette/>}><div className="grid gap-4 sm:grid-cols-2"><Select label="Theme" value={data.appearance.theme} options={["system","light","dark"]} onChange={v=>patch("appearance",{theme:v})}/><Select label="Accent" value={data.appearance.accent} options={["indigo","cyan","emerald","violet","amber"]} onChange={v=>patch("appearance",{accent:v})}/><Toggle title="Sound feedback" checked={data.appearance.sounds} onChange={v=>patch("appearance",{sounds:v})}/><Toggle title="Animations" checked={data.appearance.animations} onChange={v=>patch("appearance",{animations:v})}/></div></Panel>}
 {tab==="localization"&&<Panel title="Localization" icon={<Globe2/>}><div className="grid gap-4 sm:grid-cols-2"><Select label="Currency" value={data.localization.currency} options={["NGN","USD","GBP"]} onChange={v=>patch("localization",{currency:v})}/><Select label="Timezone" value={data.localization.timezone} options={["Africa/Lagos","UTC","Europe/London"]} onChange={v=>patch("localization",{timezone:v})}/><Select label="Date format" value={data.localization.dateFormat} options={["DD/MM/YYYY","MM/DD/YYYY","YYYY-MM-DD"]} onChange={v=>patch("localization",{dateFormat:v})}/></div></Panel>}
 {tab==="notifications"&&<Panel title="Notifications" icon={<Bell/>}><div className="space-y-3"><Toggle title="Low-stock alerts" checked={data.notifications.lowStock} onChange={v=>patch("notifications",{lowStock:v})}/><Toggle title="Payment reminders" checked={data.notifications.paymentReminders} onChange={v=>patch("notifications",{paymentReminders:v})}/><Toggle title="Security events" checked={data.notifications.securityEvents} onChange={v=>patch("notifications",{securityEvents:v})}/></div></Panel>}
 {tab==="data"&&<Panel title="Data & maintenance" icon={<Database/>}><div className="grid gap-4 sm:grid-cols-3"><Stat icon={<Wifi/>} label="Database" value="MySQL"/><Stat icon={<Wrench/>} label="Schema" value="Migrated"/><Stat icon={<SlidersHorizontal/>} label="Control" value="Local"/></div><Info text="Migrations run at startup. Product images, dynamic units, settings and split payments are additive and migration-safe."/></Panel>}
 </motion.section></main></div></div></PageContainer>}
function Panel({title,icon,children}:{title:string;icon:ReactNode;children:ReactNode}){return <div><div className="mb-6 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-indigo-50 text-indigo-600">{icon}</div><h2 className="text-xl font-black">{title}</h2></div>{children}</div>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase text-slate-400">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border px-4 py-3 text-sm font-semibold outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50"/></label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase text-slate-400">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border bg-white px-4 py-3 text-sm font-semibold">{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Toggle({title,checked,onChange}:{title:string;checked:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-center justify-between rounded-2xl border p-4"><span className="text-sm font-black">{title}</span><button onClick={()=>onChange(!checked)} className={`relative h-7 w-12 rounded-full p-1 ${checked?"bg-indigo-600":"bg-slate-200"}`}><span className={`block h-5 w-5 rounded-full bg-white shadow ${checked?"translate-x-5":""}`}/></button></div>}
function Info({text}:{text:string}){return <div className="mt-5 rounded-2xl bg-indigo-50 p-4 text-xs leading-5 text-indigo-800">{text}</div>}
function Stat({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-indigo-600">{icon}</div><p className="mt-2 text-[10px] font-black uppercase text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
